apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/storage" # minikubeにこのディレクトリを作成しておく
    type: Directory

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: weblog
    type: database
type: Opaque
data:
  keyfile: dlVRKzNOdkdFRlVxZXdmY2dKTVFsalU0T1c5Nkkyd3lwcjBqS0JUSGFwVlFHVVpXVmEzY2RvRXhTelJQMlI0WFJ0TXN5dDhnN2tRcW9OWERpRWNHNlNhd3pDS1dwTi9IUjRJZHY5WEF5N2hHWG5PT015WUF0RzhZdkxJN0phK0xEd1JsQ0c0RWp1ZzB0ZTlHZ1JzRUxiYXlRWnhTbWE1a3I1L3RXRDlTNncvMDJaeVdBNjY5RVVUbVJ5R1RraWZrQWVscHljaDR4VDF0eVVyaUtWQitHdGdBMWlBZVFVaDNkVWxuYVMzZHBTT0ZEa1ZNUER5eDMwL2JTQWdiVjhzQmZ0clZjcVYwaVNXbndCOUQvQU9JNDBwRDNmNXROSTdiQllHaEFsREs4VGFjMjdGOVB4V2Z4dzBrcm1XNkNSclNLcU1IL2pGZXpDNEhDcFVOMDh3ckpXWHBZS25XMVh2N0pUYUwrY2N2MXdHdVNLOVh3Q0wxekpXR0hGMHB0WG11SmdBVFcySHVRN25jZDI4Q0w1OE1GNUpYNTNnNk15YzdpRG1wdUw3NVJzY2ZqNjRBSkFKY1RCdXRzbzBSaFROY0lhU0oxZXlHYWtRVXZHR3J2dlNYSGU4WHNEblU1TWJjUG03QTQ3QjJPYXB3dVJhQTVOWW9BRnJaa1d4V252RXpRdnMzZXkrQXQ5MFdzeDFNMUxwbmxQYU9mNTRZMU00aG54NTJ4aS9HY1VBL21leGxpWFB6MXRaaExUc25qT2JUVS83RkppN0dFaSt6N1B6bDd0bHNNUGx2NFZLQjA3cHByS1lnb1o1RjhKWU10MnhxTUFKVzNNM1lDMzFsZDNZa1Z5b0h4dGVQTVNiTkx5eFNCTmFycmtMVHNzM0RkL1dtL3YxWEI4SmJuUzJqaUtzRTM1YjNPSFZmZW53S3JlNU9TazB0SDhneGNKREpVbjhnTExCcmpCc2p0SHBVMGw0Q2JNTy9ydVQwWVdQMm9SY3pGVlhKL1RTL01TSUlnb2Y2MVFWY3ZQUm5jOFNQN3l6LzUwRzdJNXNQdVR6VmlvNEdQT2pWQ2hmVzV1TW42aWIrZ1FoWGlkTHgxVFdwdU1yeHhXaUw2VlFxTzZwVU9rODBud2dnUjdpbUJhSGVqQklrS3JrdEM0aXFLN2cxa0toQzU4MXYzZUNQL2JNbFlBNHZwanB5dENQTmU1cGh5d1MwTXg5bk9Ed05nQ3ROSFhhNGt6ZkZKZWlNMUVySmNpNGlST2xZKzBwR3F2U0NBWVFnMUpSbUhiL3pLaHE5MlNLNTk1Ty9RUERMeHJpNW9iYnAxOExvc3BpSXpIemx1R1FPRWlRNllBeHYvckFlT05hNwo=
  root_password: UGFzc3cwcmQ=
  root_username: YWRtaW4=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  labels:
    app: weblog
    type: storage
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet # Pod
metadata:
  name: mongodb
  namespace: default
  labels:
    app: weblog
    type: database
spec:
  selector:
    matchLabels:
      app: weblog
      type: database
  serviceName: db-svc
  template:
    metadata: # ここから下が最初Podだったもの
      name: mongodb
      namespace: default
      labels:
        app: weblog
        type: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: weblog-db:v1.0.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          args: # 以下がDockerfileでENTRYPOINTに指定した.shの引数として渡されるはず
            - "mongod"
            - "--auth"
            - "--bind_ip_all"
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              valueFrom: # reference to secret resource
                secretKeyRef:
                  name: mongo-secret
                  key: root_username
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              valueFrom: # reference to secret resource
                secretKeyRef:
                  name: mongo-secret
                  key: root_password
            - name: "MONGO_INITDB_DATABASE"
              value: "admin"
          volumeMounts:
            - mountPath: /data/db # mongoコンテナの中のパス
              name: storage
            - mountPath: /home/mongodb # mongoコンテナの中のパス
              name: secret
      volumes:
        #- name: storage
        #  persistentVolumeClaim:
        #    claimName: storage-claim
        - name: secret
          secret: # volumeとして、上記のようなPVCだけでなく、secretリソースも(--from-fileでエンコード化したsecret dataのファイルとして)マウントできる！
            secretName: mongo-secret
            items:
              - key: keyfile
                path: keyfile
                mode: 0700

    volumeClaimTemplates:
      - metadata:
          name: storage
        spec:
          storageClassName: slow
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
